# -*- coding: utf-8 -*-
"""news_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAJFqnNbi4IAkWiBCXdZfVsqOWiaIFmJ
"""

import os, time, pandas as pd, requests


api_key = "ba90795e64d549e6a46600b45cc5d38c"
url = ('https://newsapi.org/v2/top-headlines?language=en&pageSize=20&'
f'apiKey={api_key}')


stream_folder = 'stream_data'
os.makedirs(stream_folder, exist_ok=True)


num_chunks = 10 # fetch 10 chunks
for file_count in range(num_chunks):
    response = requests.get(url)
    data = response.json()
    headlines = [a['title'] for a in data['articles']]
    df = pd.DataFrame(headlines, columns=['headline'])
    df.to_json(os.path.join(stream_folder,
    f'headlines_{file_count}.json'),
    orient='records', lines=True)
    print(f"Saved chunk {file_count}")
    time.sleep(30)

