# -*- coding: utf-8 -*-
"""spark_streaming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb8jMgX_mmUANAk5CiqEglG8Uxp3LnCE
"""

from pyspark.sql.types import StructType, StringType


schema = StructType().add("headline", StringType(), True)


streaming_df = spark.readStream \
  .schema(schema) \
  .json("stream_data") # folder with JSON chunks


streaming_df = streaming_df.withColumn("sentiment",
                        sentiment_udf(streaming_df['headline']))


query = streaming_df.writeStream \
  .outputMode("append") \
  .format("console") \
  .start()


query.awaitTermination(60) # stop after 60 seconds for demo