# -*- coding: utf-8 -*-
"""spark_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb8jMgX_mmUANAk5CiqEglG8Uxp3LnCE
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
from textblob import TextBlob


spark = SparkSession.builder.appName("NewsSentimentAnalysis").getOrCreate()


def get_sentiment(text):
  polarity = TextBlob(text).sentiment.polarity
  return "Positive" if polarity >= 0 else "Negative"


sentiment_udf = udf(get_sentiment, StringType())